---
version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
