---
version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    reviewers:
      - asenci
      - NoodlesNZ
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    reviewers:
      - asenci
      - NoodlesNZ
